---
- name: Test playbook
  hosts: all
  tasks:
    - name: Ping hosts
      ping:

    - set_fact: 
        db_host: "{{ hostvars[groups['reddit_db'][0]]['networkInterfaces'][0]['networkIP'] }} " 

    - debug: var=db_host 